/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kontact_pro;

import java.awt.Toolkit;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author Dumidu
 */
public class Search_Main extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Search_Main() {
        initComponents();

    }

    Search_Main(String uId) {
        initComponents();
        setIcon(); //set favicon icon

        account.setText(uId); //set user name

        list1.clear();
        Core core = new Core();
        core.dataLoad(uId);

        ArrayList<Contacts> list = core.getList();
        int size = core.dataLoad(uId);

        ArrayList<String> contactSort = new ArrayList<String>();

        // add all contacts to the list
        for (int i = 0; i < size; i++) {

             if (list.get(i).getUserRef().equalsIgnoreCase(uId)) {
            contactSort.add(list.get(i).getfName() + " " + list.get(i).getlName());
             }
        }

        Collections.sort(contactSort); //sort the result

        //print the result
        for (String conString: contactSort) {
            list1.add(conString);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        list1 = new java.awt.List();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kontact Pro");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kontact_pro/images/home.png"))); // NOI18N
        jLabel3.setToolTipText("Home");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 15, 40, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kontact_pro/images/addnew.png"))); // NOI18N
        jLabel4.setToolTipText("Add New Contact");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 15, 43, 40);

        jTextField1.setBackground(new java.awt.Color(203, 221, 253));
        jTextField1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 90, 280, 40);

        list1.setBackground(new java.awt.Color(203, 221, 253));
        list1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        list1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list1MouseClicked(evt);
            }
        });
        getContentPane().add(list1);
        list1.setBounds(200, 170, 490, 290);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kontact_pro/images/bday.png"))); // NOI18N
        jLabel2.setToolTipText("Birthday Reminders");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 15, 50, 43);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kontact_pro/images/help.png"))); // NOI18N
        jLabel5.setToolTipText("Help");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 15, 50, 40);

        account.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        account.setForeground(new java.awt.Color(255, 255, 255));
        account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        account.setToolTipText("");
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });
        getContentPane().add(account);
        account.setBounds(760, 0, 130, 40);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kontact_pro/images/logout.png"))); // NOI18N
        jLabel12.setToolTipText("Log Out");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(840, 40, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kontact_pro/images/background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 540);

        setSize(new java.awt.Dimension(912, 567));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        String uId = account.getText();
        Search_Main seMain = new Search_Main(uId);
        seMain.setLocationRelativeTo(this);
        seMain.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        String uId = account.getText();
        Log_Help help = new Log_Help(uId);
        help.setLocationRelativeTo(this);
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        String uId = account.getText();
        Add_Contact add = new Add_Contact(uId);
        add.setLocationRelativeTo(this);
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_accountMouseClicked

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:

        String x = jTextField1.getText(); // get search text
        String uId = account.getText().toLowerCase(); // get user id

        int count = 0;

        list1.clear(); //clear the list before search new
        Core core = new Core();
        int size = core.dataLoad(uId);

        ArrayList<Contacts> list = core.getList();

        // print the result searching
        for (int i = 0; i < size; i++) {

            if (list.get(i).getUserRef().equalsIgnoreCase(uId)) {
            
            String fullName = list.get(i).getfName() + " " + list.get(i).getlName();
            if (fullName.toLowerCase().startsWith(x)) {
                list1.add(fullName, count);
                count++;
            }

            }
        }


    }//GEN-LAST:event_jTextField1KeyReleased

    private void list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list1MouseClicked
        // TODO add your handling code here:
        String item = list1.getSelectedItem();
        Core core = new Core();
        
        String uId = account.getText();
        core.dataLoad(uId);
        item = core.contactId(uId, item);
        
        int len = item.length();
        
        User_Details usDetails = new User_Details(uId, item);
        usDetails.setLocationRelativeTo(this);
        usDetails.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_list1MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Log Out Successfully!", "Log Out", WIDTH);
        Login login = new Login();
        login.setLocationRelativeTo(this);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         // goto the bday reminder page
        String uId = account.getText();
        BirthDay_Reminder bday = new BirthDay_Reminder(uId);
        bday.setLocationRelativeTo(this);
        bday.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Main().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
